import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/file-explorer";
import { NoteSidebar } from "@/components/app-notebar";
import { SidebarTabs } from "@/components/sidebar-tabs";
import { ChatProvider } from "./chat-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-background text-foreground min-h-screen flex">
        <SidebarProvider>
          <ChatProvider>
            <SidebarTabs />
            <main className="flex-1 w-full h-screen overflow-auto">
              {children}
            </main>
          </ChatProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
